server:
  port: 8082

spring:
  application:
    name: transaction-service

  auth:
    service:
      url: ${AUTH_SERVICE_URL:http://localhost:8083}

  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres-transactions}:${DB_PORT:5432}/${DB_NAME:pfip_transactions}
    username: ${DB_USER:admin}
    password: ${DB_PASS:admin}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

# Must match user-service secret exactly
jwt:
  secret: ${JWT_SECRET:YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjM0NTY3ODkwYWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXo=}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    com.pfip.transactionservice: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: WARN